#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Build the two int8 calibration sets, in the order the dependency requires.

WHY THE TWO SETS ARE NOT THE SAME KIND OF THING
-----------------------------------------------
    stage 1  input is an IMAGE.       Calibrate on image paths - RKNN reads them
                                      directly, and the statistics that matter are
                                      pixel statistics.
    stage 2  input is KEYPOINTS and DESCRIPTORS, not an image.  Calibrating it on
                                      images would quantise the wrong distribution
                                      entirely: the matcher never sees a pixel.  It
                                      needs `.npy` samples of stage-1's OUTPUT.

AND WHY STAGE 2 MUST BE CALIBRATED ON *QUANTISED* STAGE-1 OUTPUT
---------------------------------------------------------------
The convenient thing to do is dump stage-1's float32 outputs and calibrate on
those.  It is also wrong, and quietly so: the matcher's activation ranges will be
fitted to a distribution it never sees at runtime, because at runtime its input is
whatever a QUANTISED stage 1 produced.  int8 output has its own error
characteristics - a different noise floor, different tails - and those are exactly
what decides the quantisation ranges of the first layer of the matcher.

So the order is forced, and that is why this script has two phases:

    1. convert stage 1 to int8 (images as calibration)
    2. run THAT model to produce the stage-2 calibration samples
    3. convert stage 2 to int8 on those samples

Step 2 needs the `.rknn` from step 1, so `--phase` splits the work and
`--stage1-rknn` carries it across.  A script that did all three in one process
would have to hold both an int8 stage-1 model and a quantising stage-2 build, and
would make the dependency invisible.

Usage
    # phase 1: stage-1 image list, and convert stage 1 to int8
    python scripts/make_calib.py --phase images --n 200 --out refs/calib_stage1.txt

    # phase 2: stage-2 tensor samples, generated by the int8 stage 1 (build it
    # first: convert_to_rknn.py ... --dtype i8 --dataset refs/calib_stage1.txt)
    python scripts/make_calib.py --phase tensors --n 200 \
        --stage1-rknn refs/alike_stage_bil_i8.rknn \
        --out-dir refs/calib_stage2 --out refs/calib_stage2.txt
"""
import argparse
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))
import paths  # noqa: E402





def collect_images(n, seed=0):
    """A pool drawn from the open-source HPatches sequences.

    Calibration ranges come from the activation distribution, so the pool has to
    span the images the model will actually see.  HPatches is the benchmark this
    deployment is measured on, and every sequence is walked rather than a subset,
    so no single scene dominates the fit.

    The order is fixed by sorted sequence/query name rather than by a shuffle, so
    the same seed gives the same list on any machine.
    """
    hpatches = paths.hpatches()
    seqs = ([s for s in sorted(hpatches.iterdir()) if s.is_dir()]
            if hpatches.is_dir() else [])
    # Query index OUTER, sequence INNER.  Walking sequence-by-sequence instead
    # would spend the first `n` samples inside the first handful of scenes, which
    # is a narrower activation distribution than the benchmark actually has; this
    # way any prefix already spans every sequence.
    out = []
    for q in ("1.ppm", "2.ppm", "3.ppm", "4.ppm", "5.ppm", "6.ppm"):
        for s in seqs:
            p = s / q
            if p.is_file():
                out.append(p)
                if len(out) >= n:
                    return out
    if not out:
        raise SystemExit(f"no calibration images found under {hpatches}")
    return out


def phase_images(args):
    """Write stage-1 calibration samples as `.npy`, one IMAGE per sample.

    ONE IMAGE PER SAMPLE
    --------------------
    Stage 1 is exported at `--batch 1`: the extractor runs once per image and a pair
    is two calls.  A calibration sample therefore IS one image - `(1, S, S, 3)`
    uint8 - and no pairing is involved any more.  (Before the per-image change the
    batch dimension had to be filled with both views of a pair, which is why this
    function used to build `(2, S, S, 3)` samples.)

    WHY NOT IMAGE PATHS, WHICH IS THE OBVIOUS THING
    -----------------------------------------------
    Now that the model is batch 1, a path would satisfy the shape and the build
    would accept it - so the reason is no longer the shape.  It is the PIXELS: a
    path goes through RKNN's own image reader (its resize, its colour conversion),
    while a `.npy` is raw tensor data that this script has already converted
    exactly the way the rest of the pipeline reads images.  It also keeps the one
    thing a calibration set must not have - an implicit difference between what is
    quantised and what is deployed.

    LAYOUT: A `.npy` IS READ AS NCHW, AN IMAGE PATH AS NHWC
    ------------------------------------------------------
    Both were measured (on the batch-2 graph, where the shapes were
    `(2,S,S,3)`/`(2,3,S,S)`; the layout rule is unchanged).  An image path is loaded
    by RKNN's image reader and arrives as NHWC.  A `.npy` is taken as raw tensor
    data and must already be in the model's layout, so it is saved transposed into
    NCHW.  The two paths do not agree, and the NCHW error only appears once the
    NHWC one is fixed.
    """
    import cv2
    from collections import Counter

    imgs = collect_images(args.n)
    if not imgs:
        # Deliberately not resolved through paths.* here: this branch runs when
        # there is nothing to read, and a second resolution failure would replace
        # the message the user needs with a different one.
        raise SystemExit("no calibration images found; set HPATCHES_ROOT, or pass "
                         "--n smaller (see paths.py)")

    out_dir = Path(args.out).parent / "calib_stage1"
    out_dir.mkdir(parents=True, exist_ok=True)

    lines, srcs = [], []
    for i, ip in enumerate(imgs):
        im = cv2.imread(str(ip), cv2.IMREAD_GRAYSCALE)
        if im is None:
            continue
        im = cv2.resize(im, (args.size, args.size), interpolation=cv2.INTER_LINEAR)
        # NHWC for reading, NCHW for saving - see the docstring.
        u8 = np.stack([np.stack([im] * 3, -1)]).astype(np.uint8)
        p = out_dir / f"img_{i:04d}.npy"
        np.save(p, np.ascontiguousarray(u8.transpose(0, 3, 1, 2)))
        lines.append(str(p.resolve()))
        srcs.append(f"{ip.parent.name}/{ip.name}")

    if not lines:
        raise SystemExit("no usable calibration samples were produced")
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"[calib] {len(lines)} stage-1 samples of shape "
          f"(1, 3, {args.size}, {args.size}) NCHW -> {args.out}")
    print("        by source:", dict(Counter(s.split('/')[0] for s in srcs)))
    return 0


def hpatches_pairs(n):
    """Two frames of the same sequence: (query, reference) from HPatches.

    Only the stage-2 phase needs pairs, because the matcher consumes two feature
    sets at once.  Stage 1 is per-image, so its samples are single images
    (`collect_images`).

    A real image PAIR rather than one frame duplicated into both views: a
    calibration sample built by repeating a single frame would present the matcher
    with two identical descriptor sets - a degenerate input it never sees at
    runtime, and exactly the kind of narrow activation range that produces a bad
    quantisation fit.

    Frames 1 and 2 of a sequence differ by the sequence's own viewpoint or
    illumination change, which is the variation the benchmark is made of.
    """
    root = paths.hpatches()
    seqs = ([s for s in sorted(root.iterdir()) if s.is_dir()]
            if root.is_dir() else [])
    out = []
    for s in seqs:
        a, b = s / "1.ppm", s / "2.ppm"
        if a.is_file() and b.is_file():
            out.append((a, b))
            if len(out) >= n:
                break
    return out


def phase_tensors(args):
    """Run the QUANTISED stage 1 to produce stage-2 calibration samples.

    The output is a dataset file with one line per sample, four `.npy` paths per
    line in the order the matcher's ONNX declares its inputs
    (`keypoints0, keypoints1, descriptors0, descriptors1`).  RKNN takes a
    multi-input dataset in that form; a single path per line is only correct for a
    single-input model.
    """
    import cv2
    from rknn.api import RKNN


    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    pairs = hpatches_pairs(args.n)
    if not pairs:
        raise SystemExit(f"no HPatches pairs found under {paths.hpatches()}")

    # The QUANTISED stage 1, rebuilt from the ONNX it was converted from, because
    # the simulator only exists on the load+build path.  Using the float32 stage 1
    # here would defeat the entire point of this phase.
    rk = RKNN(verbose=True)          # verbose AT CONSTRUCTION: see convert_to_rknn
    cfg = {"target_platform": args.target, "float_dtype": "float16"}
    cfg["mean_values"] = [[0, 0, 0]]
    cfg["std_values"] = [[255, 255, 255]]
    rk.config(**cfg)
    if rk.load_onnx(model=str(args.s1_onnx)) != 0:
        raise SystemExit("load_onnx failed for stage 1")
    quantise = args.stage1_quantised
    if rk.build(do_quantization=quantise,
                dataset=args.stage1_dataset if quantise else None) != 0:
        raise SystemExit("stage-1 build failed")
    rk.init_runtime(target=None)
    print(f"[calib] stage 1 built {'QUANTISED' if quantise else 'fp16'}"
          + (f" (dataset={args.stage1_dataset})" if quantise else ""))

    def extract(img):
        """One per-image stage-1 call -> (keypoints (1,K,2), descriptors (1,K,128))."""
        u8 = np.stack([np.stack([img] * 3, -1)]).astype(np.uint8)   # (1,S,S,3)
        outs = [np.asarray(o) for o in
                rk.inference(inputs=[u8], data_format="nhwc")]
        k = next(o for o in outs if o.ndim == 3 and o.shape[-1] == 2).astype(np.float32)
        d = next(o for o in outs if o.ndim == 3 and o.shape[-1] == 128).astype(np.float32)
        return k, d

    lines, n_ok = [], 0
    for i, (vp, tp) in enumerate(pairs):
        a = cv2.imread(str(vp), cv2.IMREAD_GRAYSCALE)
        b = cv2.imread(str(tp), cv2.IMREAD_GRAYSCALE)
        if a is None or b is None or a.shape != b.shape:
            continue
        a = cv2.resize(a, (args.size, args.size), interpolation=cv2.INTER_LINEAR)
        b = cv2.resize(b, (args.size, args.size), interpolation=cv2.INTER_LINEAR)
        # Stage 1 is per-image, so the pair is TWO calls and the two feature sets
        # become the matcher's four inputs.
        k0, d0 = extract(a)
        k1, d1 = extract(b)

        # One sample per PAIR: the matcher's four inputs are (k0, k1, d0, d1), and
        # splitting a pair across two samples would double the count while halving
        # the diversity.
        stem = f"{i:04d}"
        # NB: not `paths` - that name belongs to the imported module, and
        # rebinding it here turned a `paths.*` call in this same function into an
        # UnboundLocalError the moment this line ran.
        npy_paths = []
        for tag, arr in (("k0", k0), ("k1", k1), ("d0", d0), ("d1", d1)):
            p = out_dir / f"{stem}_{tag}.npy"
            np.save(p, arr)
            npy_paths.append(str(p.resolve()))
        lines.append(" ".join(npy_paths))
        n_ok += 1
        if (i + 1) % 25 == 0:
            print(f"    [{i+1}/{len(pairs)}] samples written")
    rk.release()

    if not lines:
        raise SystemExit("no samples produced - check the image reading above")
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(lines) + "\n")
    print(f"[calib] {n_ok} samples ({n_ok * 4} .npy files) -> {args.out}")
    print("[calib] dataset file has 4 paths per line, in the matcher's input order")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", required=True, choices=["images", "tensors"])
    ap.add_argument("--n", type=int, default=200)
    ap.add_argument("--out", required=True)
    ap.add_argument("--out-dir", default=None, help="phase tensors: where the .npy go")
    ap.add_argument("--size", type=int, default=512)
    ap.add_argument("--target", default="rk3588")
    ap.add_argument("--s1-onnx", default=str(REPO / "weights/original/alike_stage_bil.onnx"))
    ap.add_argument("--stage1-dataset", default=None,
                    help="phase tensors: the stage-1 image list, so stage 1 is built "
                         "QUANTISED.  Without it the samples would come from a "
                         "float32 model and the calibration would be fitted to a "
                         "distribution the matcher never sees.")
    ap.add_argument("--stage1-quantised", action="store_true",
                    help="generate the samples from an int8 stage 1.  Default is "
                         "fp16, because int8 stage 1 loses too much accuracy to "
                         "ship - see the int8 report - so calibrating "
                         "stage 2 on its output would fit a distribution that no "
                         "deployable pipeline produces.")
    ap.add_argument("--stage1-rknn", default=None,
                    help="phase tensors: recorded for provenance; the rebuild uses "
                         "`--s1-onnx` because the simulator has no load_rknn path")
    args = ap.parse_args()

    if args.phase == "images":
        return phase_images(args)
    if args.stage1_quantised and not args.stage1_dataset:
        ap.error("--stage1-quantised needs --stage1-dataset (the image list)")
    if not args.out_dir:
        ap.error("--phase tensors needs --out-dir")
    return phase_tensors(args)


if __name__ == "__main__":
    sys.exit(main())
